### ISSUE TITLE
Weight Axis variable font

### ISSUE THREAD

**Issue by pichotta** [magictype/redrose#6]
@jaikishanpatel 

Hello Jaikishan,

The Google fonts team would love to see a variable font version of ‘Red Rose'. They have commissioned us @TypeNetwork to work on upgrading a number of font projects to be variable fonts with a single weight axis.

In order to achieve the highest quality and most efficient long term results we will be converting the source data from Glyphs to UFO. The new source data will be generated in the RoboFont environment using fontmake and ttfautohint. There has been progress on tools to make an easy path to move between the Glyphs and Robofont environment.

During the process we will be looking to improve any errors while preserving how the font appears and renders on different platforms.

We have started by making a fork off of this git repository. The upgrade will be completed for you in the near future. When the proposed final font is approved by Google they will accept a pull request.

We hope this answers some of your questions about the process. Please let us know if you have any additional comments.

Best Regards,

Jill Pichotta
Vice President
Type Network
pichotta@typenetwork.com

**Comment by jaikishanpatel** [comment]
Thanks you so much @pichotta @TypeNetwork

**Comment by pichotta** [comment]
@jaikishanpatel

Hello Jaikishan,

The work on the weight axis variable font for **Red Rose** is complete and has been integrated upstream.

https://github.com/google/fonts/pull/2691

https://github.com/TypeNetwork/redrose/tree/master/fonts/variable

Best,

Jill
